# Generated by Django 5.2.3 on 2025-07-14 01:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Estilo Artístico')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Material de la Escultura')),
            ],
            options={
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='MuseoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Museo')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('enlace_catalogo', models.URLField(max_length=255, verbose_name='Enlace al Catálogo Externo')),
            ],
            options={
                'verbose_name': 'Museo Colaborador',
                'verbose_name_plural': 'Museos Colaboradores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Periodo Histórico')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('especialidad', models.CharField(choices=[('CU', 'Cuadros'), ('ES', 'Esculturas')], max_length=2, verbose_name='Especialidad')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado Laboral')),
                ('ocupado', models.BooleanField(default=False, verbose_name='¿Está ocupado en una restauración?')),
            ],
            options={
                'verbose_name': 'Restaurador',
                'verbose_name_plural': 'Restauradores',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Sala')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Técnica del Cuadro')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMuseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='catalogo.museocolaborador')),
            ],
        ),
        migrations.CreateModel(
            name='ObraDeArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='obras/', verbose_name='Imagen de la Obra')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('valoracion_economica', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valoración Económica (S/)')),
                ('fecha_creacion', models.CharField(help_text="Introduzca la fecha en formato dd/mm/aaaa o escriba 'Desconocida'.", max_length=50, verbose_name='Fecha de Creación')),
                ('fecha_entrada_museo', models.DateField(verbose_name='Fecha de Entrada al Museo')),
                ('estado', models.CharField(choices=[('EX', 'En exposición'), ('RE', 'En restauración'), ('CE', 'Cedida'), ('BO', 'En Bodega')], default='BO', max_length=2, verbose_name='Estado')),
                ('tipo_obra', models.CharField(choices=[('CU', 'Cuadro'), ('ES', 'Escultura')], max_length=2, verbose_name='Tipo de Obra')),
                ('estilo', models.ManyToManyField(to='catalogo.estilo', verbose_name='Estilo(s) Artístico(s)')),
                ('material', models.ManyToManyField(blank=True, to='catalogo.material', verbose_name='Material(es) (si es escultura)')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.periodo', verbose_name='Periodo')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.sala', verbose_name='Sala de Ubicación')),
                ('tecnica', models.ManyToManyField(blank=True, to='catalogo.tecnica', verbose_name='Técnica(s) (si es cuadro)')),
            ],
            options={
                'verbose_name_plural': 'Obras de Arte',
            },
        ),
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Exhibición')),
                ('imagen', models.ImageField(upload_to='exhibiciones/', verbose_name='Imagen para el Carrusel')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('obras_incluidas', models.ManyToManyField(blank=True, to='catalogo.obradearte', verbose_name='Obras Incluidas en la Exhibición')),
            ],
            options={
                'verbose_name': 'Exhibición',
                'verbose_name_plural': 'Exhibiciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio de la Cesión')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin de la Cesión')),
                ('museo_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.museocolaborador', verbose_name='Museo Destino')),
                ('obras_cedidas', models.ManyToManyField(to='catalogo.obradearte', verbose_name='Obras Cedidas')),
            ],
            options={
                'verbose_name': 'Cesión',
                'verbose_name_plural': 'Cesiones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Restauracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('informe_danos', models.TextField(verbose_name='Informe de Daños / Motivo')),
                ('tipo_restauracion', models.CharField(max_length=200, verbose_name='Tipo de Restauración Realizada')),
                ('obra_a_restaurar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restauraciones', to='catalogo.obradearte', verbose_name='Obra a Restaurar')),
                ('restauradores_asignados', models.ManyToManyField(to='catalogo.restaurador', verbose_name='Equipo de Restauradores Asignado')),
            ],
            options={
                'verbose_name': 'Restauración',
                'verbose_name_plural': 'Restauraciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_solicitud', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_solicitud', models.DateField(verbose_name='Fecha de Fin')),
                ('museo_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.museocolaborador', verbose_name='Museo al que se solicita')),
            ],
            options={
                'verbose_name': 'Solicitud de Cesión',
                'verbose_name_plural': 'Solicitudes de Cesión',
                'ordering': ['-fecha_inicio_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ObraSolicitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra', models.CharField(max_length=255, verbose_name='Nombre de la Obra')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_solicitadas', to='catalogo.solicitudcesion')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoMuseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="El número de teléfono solo puede contener números, espacios y el símbolo '+' al inicio.", regex='^\\+?[\\d\\s]+$')], verbose_name='Número de Teléfono')),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='catalogo.museocolaborador')),
            ],
        ),
    ]
