# Generated by Django 5.2.3 on 2025-06-27 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Estilo Artístico')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Material de la Escultura')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Periodo Histórico')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Sala')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Técnica del Cuadro')),
            ],
        ),
        migrations.CreateModel(
            name='ObraDeArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('valoracion_economica', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valoración Económica (€)')),
                ('fecha_creacion', models.CharField(blank=True, max_length=50, verbose_name='Fecha de Creación')),
                ('fecha_entrada_museo', models.DateField(verbose_name='Fecha de Entrada al Museo')),
                ('estado', models.CharField(choices=[('EX', 'En exposición'), ('RE', 'En restauración'), ('CE', 'Cedida'), ('BO', 'En Bodega')], default='BO', max_length=2, verbose_name='Estado')),
                ('tipo_obra', models.CharField(choices=[('CU', 'Cuadro'), ('ES', 'Escultura')], max_length=2, verbose_name='Tipo de Obra')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.estilo', verbose_name='Estilo Artístico')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.material', verbose_name='Material (si es escultura)')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.periodo', verbose_name='Periodo')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.sala', verbose_name='Sala de Ubicación')),
                ('tecnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.tecnica', verbose_name='Técnica (si es cuadro)')),
            ],
        ),
    ]
