# Generated by Django 5.2.3 on 2025-06-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obradearte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obras/', verbose_name='Imagen de la Obra'),
        ),
        migrations.AlterField(
            model_name='obradearte',
            name='valoracion_economica',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valoración Económica (S/)'),
        ),
    ]
