# Generated by Django 5.2.3 on 2025-06-28 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_obradearte_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('especialidad', models.CharField(blank=True, max_length=150, verbose_name='Especialidad (ej. Pintura, Escultura)')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
                ('ocupado', models.BooleanField(default=False, verbose_name='¿Está ocupado en una restauración?')),
            ],
            options={
                'verbose_name': 'Restaurador',
                'verbose_name_plural': 'Restauradores',
            },
        ),
        migrations.CreateModel(
            name='Restauracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('informe_danos', models.TextField(verbose_name='Informe de Daños / Motivo')),
                ('tipo_restauracion', models.CharField(max_length=200, verbose_name='Tipo de Restauración Realizada')),
                ('obra_a_restaurar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restauraciones', to='catalogo.obradearte', verbose_name='Obra a Restaurar')),
                ('restauradores_asignados', models.ManyToManyField(to='catalogo.restaurador', verbose_name='Equipo de Restauradores Asignado')),
            ],
            options={
                'verbose_name': 'Restauración',
                'verbose_name_plural': 'Restauraciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
