# Generated by Django 5.2.3 on 2025-06-28 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_restaurador_restauracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Museo')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('persona_contacto', models.CharField(blank=True, max_length=200, verbose_name='Persona de Contacto')),
            ],
            options={
                'verbose_name': 'Museo Colaborador',
                'verbose_name_plural': 'Museos Colaboradores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio de la Cesión')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin de la Cesión')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe de la Cesión (S/)')),
                ('obra_cedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cesiones', to='catalogo.obradearte', verbose_name='Obra Cedida')),
                ('museo_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.museocolaborador', verbose_name='Museo Destino')),
            ],
            options={
                'verbose_name': 'Cesión',
                'verbose_name_plural': 'Cesiones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
