# Generated by Django 5.2.3 on 2025-06-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_museocolaborador_cesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Exhibición')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('obras_incluidas', models.ManyToManyField(blank=True, to='catalogo.obradearte', verbose_name='Obras Incluidas en la Exhibición')),
            ],
            options={
                'verbose_name': 'Exhibición',
                'verbose_name_plural': 'Exhibiciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
