# Generated by Django 5.2.3 on 2025-06-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_exhibicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibicion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='exhibiciones/', verbose_name='Imagen para el Carrusel'),
        ),
    ]
