# Generated by Django 5.2.3 on 2025-06-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_exhibicion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obradearte',
            name='titulo',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título'),
        ),
    ]
