# Generated by Django 5.2.3 on 2025-06-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_obradearte_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurador',
            options={'ordering': ['apellidos', 'nombre'], 'verbose_name': 'Restaurador', 'verbose_name_plural': 'Restauradores'},
        ),
        migrations.RemoveField(
            model_name='restaurador',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='restaurador',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='restaurador',
            name='apellidos',
            field=models.CharField(default='Apellido Temporal', max_length=150, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurador',
            name='email',
            field=models.EmailField(default='temporal@museo.com', max_length=254, unique=True, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurador',
            name='nombre',
            field=models.CharField(default='Nombre Temporal', max_length=100, verbose_name='Nombre(s)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurador',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='restaurador',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado Laboral'),
        ),
    ]
