# Generated by Django 5.2.3 on 2025-07-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_restaurador_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesion',
            name='importe',
        ),
    ]
