# Generated by Django 5.2.3 on 2025-07-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_remove_cesion_importe'),
    ]

    operations = [
        migrations.AddField(
            model_name='museocolaborador',
            name='enlace_catalogo',
            field=models.URLField(blank=True, max_length=255, verbose_name='Enlace al Catálogo Externo'),
        ),
    ]
