# Generated by Django 5.2.3 on 2025-07-12 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_museocolaborador_enlace_catalogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museocolaborador',
            name='persona_contacto',
        ),
        migrations.AlterField(
            model_name='museocolaborador',
            name='enlace_catalogo',
            field=models.URLField(max_length=255, verbose_name='Enlace al Catálogo Externo'),
        ),
        migrations.CreateModel(
            name='EmailMuseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='catalogo.museocolaborador')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoMuseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número de Teléfono')),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='catalogo.museocolaborador')),
            ],
        ),
    ]
