# Generated by Django 5.2.3 on 2025-07-12 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_remove_museocolaborador_persona_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonomuseo',
            name='numero',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="El número de teléfono solo puede contener números, espacios y el símbolo '+' al inicio.", regex='^\\+?[\\d\\s]+$')], verbose_name='Número de Teléfono'),
        ),
    ]
