# Generated by Django 5.2.3 on 2025-07-12 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_telefonomuseo_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_solicitada', models.CharField(max_length=255, verbose_name='Nombre de la Obra Solicitada')),
                ('fecha_inicio_solicitud', models.DateField(verbose_name='Fecha de Inicio Deseada')),
                ('fecha_fin_solicitud', models.DateField(verbose_name='Fecha de Fin Deseada')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada')], default='P', max_length=1, verbose_name='Estado de la Solicitud')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('museo_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.museocolaborador', verbose_name='Museo al que se solicita')),
            ],
            options={
                'verbose_name': 'Solicitud de Cesión',
                'verbose_name_plural': 'Solicitudes de Cesión',
                'ordering': ['-fecha_inicio_solicitud'],
            },
        ),
    ]
